### ISSUE TITLE
5000:Something went wrong - Detailed Code 3104 - Custom Connector SDK sample

### ISSUE THREAD

**Issue by pealmasa** [microsoftgraph/msgraph-connectors-sdk#10]
Used this custom connector sample to deploy on my dev test tenant and everything is working fine, from Agent perspective
GCA test app all ok. 
Connector shows Ready state.
The connector was registered successfully but I still get the 5000/3104 error for all data source items.

**Comment by pealmasa** [comment]
This is a false issue. Actually, the incremental crawl method was not implemented therefore all increment connector calls were failing. Changed the connector to ful crawl 30 mins in 30 mins and got all items indexed

![image](https://github.com/microsoftgraph/msgraph-connectors-sdk/assets/11350767/0a8dce7d-0fad-4428-ad9f-0f91cc8955d2)

**Comment by Vish6300** [comment]
Hi @pealmasa, can you confirm once, while configuring the connection did you add additionalCrawlsSupported with Incremental in the manifest.

**Comment by pealmasa** [comment]
@Vish6300 no. I have used this manifest

![image](https://github.com/microsoftgraph/msgraph-connectors-sdk/assets/11350767/eb999e15-638b-4924-ae88-baff5ffefee6)

**Comment by Vish6300** [comment]
Hi @pealmasa, according to this you have not enabled incremental crawl and should not be able to get the option for scheduling incremental crawl. I am not sure how your issue got resolved since incremental crawl should not be getting triggered
