### ISSUE TITLE
Errors when running Website connector through Agent

### ISSUE THREAD

**Issue by mncannava** [microsoftgraph/msgraph-connectors-sdk#11]
When configuring the Website connector through an on-prem Agent using Windows Authentication through Okta, we're getting the following errors:

5000: Something went wrong, if this continues, contact support. Detailed error code: 6015.

The crawl stops at that point and we are unsure how to proceed.

**Comment by rchanda1392** [comment]
Closing this since it is not an issue related to the SDK.
