### ISSUE TITLE
Error while crawling Items in Custom Connector

### ISSUE THREAD

**Issue by SonuGourkhede** [microsoftgraph/msgraph-connectors-sdk#13]
I have reconfigure custom connector for Insight. All the items are getting error out.
Getting below error :-
06/23/2023 11:26:52,60517-en-GB,5000,3004,Something went wrong. If this continues, contact support.

![CustomConnector](https://github.com/microsoftgraph/msgraph-connectors-sdk/assets/103108278/7bf915e2-dc50-4aeb-b5fe-eb9c6763769a)

**Comment by Vish6300** [comment]
Hi @SonuGourkhede, after checking the logs we found out that the connection deletion process was partially completed and a crawl got triggered during connection deletion and as a result during item ingestion, 404  was coming since connection shard is not found.

**Comment by Vish6300** [comment]
Kindly close this if this issue has been resolved

**Comment by SonuGourkhede** [comment]
The issue has been resolved we have reconfigure our custom connector.
