### ISSUE TITLE
How can I retrieve the connector Id from the connector for external groups?

### ISSUE THREAD

**Issue by eborisowIQVIA** [microsoftgraph/msgraph-connectors-sdk#18]
Hi all,

I am trying to create external groups associated with my connector.
e.g. https://graph.microsoft.com/v1.0/external/connections/<connector id>/groups

The connector id is determined by the admin creating the connector.  It would be great if we can receive the connector id during getCrawlStream.  I can't seem to find any objects that represent the connector-specific config.  Other than stuffing it into the custom config, is there any other way to retrieve that data?

**Comment by rchanda1392** [comment]
Hello @eborisowIQVIA , do you mean "connectionId" and not the "connectorId"?
ConnectorId identifies the type of your custom connector- it is a constant.
ConnectionId is the instance of the connector that you're creating. One connector(Id) can have multiple connection(Id)s associated with it.
Can you help us understand the use case you're trying to solve?

**Comment by eborisowIQVIA** [comment]
In my case, I'm trying to create arbitrary groups using a combination of connector name prefix plus a unique value from the content.  I may also use the connector name prefix for other uses, such as prefixing logs so that I can distinguish two connectors pointing at the same data source.

**Comment by rchanda1392** [comment]
Hi @eborisowIQVIA this capability is not supported at the moment in the SDK. Hence the SDK won't be able to ACL content using external groups (https://learn.microsoft.com/en-us/graph/custom-connector-sdk-overview#microsoft-graph-connector-agent-capabilities).
It is not recommended to create the connector using the SDK and then ACL the content using the Graph API as we do not know if the behaviour will be consistent. The Graph API team will be able to guide you if you have further questions.

**Comment by eborisowIQVIA** [comment]
Thanks, Chanda.  So, just to summarize, my thought was:

During crawl:
a) Pull data from data source.
b) Add properties to crawlstreambit.
c) Add ACL for external group based on connector.  e.g. ConnectorName-GroupName
d) notify observer

On completion of the crawl:
a) Create an external group named ConnectorName-GroupName
b) Add members which are users with an AAId

Assumption being that a user who is part of the group can now see the crawled item.  Is that what is not supported?
