### ISSUE TITLE
Unable to crawl items using a worker service with GCA 1.8.3.0

### ISSUE THREAD

**Issue by FranckyC** [microsoftgraph/msgraph-connectors-sdk#5]
I'm currently implementing a custom connector using following the documentation from [here](https://learn.microsoft.com/en-us/graph/custom-connector-sdk-sample-create). However, I'm not able to crawl items using a worker service after followed these [steps](https://learn.microsoft.com/en-us/graph/custom-connector-sdk-sample-hosting).

Checking the connection logs (C:\Users\GcaHostService\AppData\Local\Microsoft\GraphConnectorAgent\<connection_name>) displays the following error without any other details:

```
System.AggregateException: One or more errors occurred. (Fetching items from datasource failed)
 ---> Microsoft.Graph.Connectors.Framework.Model.ErrorHandling.Exceptions.ConnectorTransientException: Fetching items from datasource failed
   at Microsoft.Graph.Connectors.OnPremAgent.GrpcBridge.ErrorHandler.GenericGrpcErrorMapper.ThrowExceptionFromOperationStatus(OperationStatus operationStatus, Boolean isCrawlFlow) in D:\dbs\el\8732\sources\dev\GCS\OnPremAgent\GrpcBridge\ErrorHandler\GenericGrpcErrorMapper.cs:line 88
   at Microsoft.Graph.Connectors.OnPremAgent.GrpcBridge.Wrappers.GrpcAllItemsEnumerator.MoveNext(CancellationToken cancellationToken) in D:\dbs\el\8732\sources\dev\GCS\OnPremAgent\GrpcBridge\Wrappers\GrpcAllItemsEnumerator.cs:line 102
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Graph.Connectors.OnPremAgent.AgentLibrary.Actors.CrawlWorkerHelper.FetchNextBatch(NextItemsBatchResponse response) in D:\dbs\el\8732\sources\dev\GCS\OnPremAgent\Microsoft.Graph.Connectors.OnPremAgent.AgentLibrary\Actors\CrawlWorkerHelper.cs:line 175
```

The connector ID and port are correctly set in the `CustomConnectorPortMap.json` file and the crawl process works fine running the application without the service (i.e just by starting the console application .exe file). Also, I don't get any errors from the event logs and I can confirm the service is correctly listening on the specified port. The service is running using "LocalSystem" and I'm using GCA **1.8.3.0**.

Is there anything I can check to debug the root cause of the issue? Thanks!

**Comment by mashi16** [comment]
The error is thrown based on the OperationResult sent from the connector. Can you check the connector log as why the operationResult was set as OperationResult.DatasourceError.

**Comment by Vish6300** [comment]
You can check connector logs at C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\<Connector Name>\Logs\ConnectorLog.log if you are using https://marketplace.visualstudio.com/items?itemName=ms-graph-connectors.graphConnectors this extension with **version 2.1**. For earlier versions we did not have the capability to maintain connector logs when running connector as a windows service.

**Comment by rchanda1392** [comment]
@FranckyC please let us know if you're still unable to crawl items.

**Comment by FranckyC** [comment]
Unfortunately I don't have any logs in the mentioned path. Should I recreate the connector using the latest template?

**Comment by Vish6300** [comment]
Yes, you need to recreate the connector using the latest version and in connectorServer.cs file you need to change the connector name parameter with your connector name

**Comment by FranckyC** [comment]
Tested with latest version and same behavior. Not log file at "C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft" and same error message.

**Comment by FranckyC** [comment]
@Vish6300 After adding the `server.StartLogger();` line in the `Worker.cs` file, I was able to see logs. It appears the error was because the `App.config` configuration file used in the main project wasn't in the worker service project. Adding this file to the worker service project resolved the issue. Thanks for your help!

Also it seems using a self-contained publish profile with a single file does not work. Don't know really why but maybe it would be worth it to test this scenario on your end.

**Comment by Vish6300** [comment]
Thanks @FranckyC for the update. Sure, will definitely investigate this scenario further.
