### ISSUE TITLE
No option to create "Custom Connector"

### ISSUE THREAD

**Issue by meganschauersnavex** [microsoftgraph/msgraph-connectors-sdk#6]
I don't see any option to create "Custom Connector" at the page below:
https://admin.microsoft.com/Adminportal/Home#/MicrosoftSearch/Connectors/add 

I'm following step #3 in "Publish your custom Microsoft Graph connector" at the page below:
https://learn.microsoft.com/en-us/graph/custom-connector-sdk-sample-publish 

Tenant: navexcmd
I've tested my Microsoft Graph connector, "GraphConnectorAgentTest" and tests 1, 2, and 3 successful.

**Comment by rchanda1392** [comment]
Hi @meganschauersnavex, for accessing the option please join the targeted release ring using the instructions here: https://learn.microsoft.com/en-us/microsoft-365/admin/manage/release-options-in-office-365?view=o365-worldwide

Let us know if you'd need further help.

**Comment by meganschauersnavex** [comment]
How long will Custom Connector be in preview?
Is it recommended to use Azure with the SDK, or use the Custom Connector?

**Comment by rchanda1392** [comment]
@meganschauersnavex We're expecting to make this publicly available in the current quarter (CY23Q1).
Not sure what you mean by using Azure with the SDK. Can you please explain?

**Comment by meganschauersnavex** [comment]
Good to know, and yes, I've been looking at following one of these two tutorials:
- https://learn.microsoft.com/en-us/graph/custom-connector-sdk-sample-publish
- https://learn.microsoft.com/en-us/graph/connecting-external-content-build-quickstart

**Comment by meganschauersnavex** [comment]
Also, how do I publish a connection to the data source list? 
![image](https://user-images.githubusercontent.com/83420501/217615129-f79e034e-91a0-4813-921a-3a651a2044b8.png)
Should I use the SDK or graph APIs directly?

**Comment by rchanda1392** [comment]
@meganschauersnavex you should use the API/SDK depending on your use case. We recommend using the SDK in case you do not want to write a lot of common logic that are required for all connectors and only want to do your data source specific configuration. You may use the APIs in case you have a lot of custom logic that you'd want to implement.

You cannot publish API based connectors from the M365 admin center. Only SDK based connectors can be published and managed from the admin center. In case you're still not able to see the "custom connector" option or if you'd like to have a quick chat about your use case or discuss further, please drop a message to rchanda@microsoft.com.
